name: Matthew Freidell
favicon: null
layout_spectrum: 0.9824319479521364
typography_spectrum: 0.18516347324475646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.527426949236542
  lightness: 0.43433585995808244
  saturation: 0.04598307330161333
  rhythmicContrast: 0.04389970097690821
purpose: []
